# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5334b60f6f2b5a0e758bd274cabd7b7c965a5f44f9d3a9ad10e158a3c6050dfa69a219f26b41da2ac121c60a4d212c887fc9a60c2a320e898bf201865dce81e

test:
  secret_key_base: 78adfa9a8383655e20480609932317df42f922a24fefa82c052346ef047bfb1c05e6abaa70062f28054666d34b4b715db2eabe884f6c341568b1411746911322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
